# Generated by Django 5.1.3 on 2024-12-01 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_martialartsclass_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'martial_arts_class', 'schedule')},
        ),
    ]
