# Generated by Django 5.1.3 on 2024-12-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_feedback_unique_together_feedback_schedule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrollment_date']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
